### ISSUE TITLE
Error on each link

### ISSUE THREAD

**Issue by friedrich-vlinde** [noitcudni/bing-webmaster-tools-bulk-url-removal#1]
I am getting an error on each link submited. See image bellow.
![image](https://user-images.githubusercontent.com/65901478/193786331-f092eafc-e25e-46af-aed4-bd792b8a9131.png)

It also takes like 15 seconds per check/add and I have 10k links to submit...

**Comment by noitcudni** [comment]
Got it. Can you send me your csv file? I'll try to reproduce it on my end. My email is lihster.developer@gmail.com

**Comment by noitcudni** [comment]
I'm going to look into this in the next couple days. Thanks for your patience

**Comment by noitcudni** [comment]
Looks like adding a timeout in between calls helps. I'm going to play around with that a bit
