### ISSUE TITLE
Bulk URL removal tool is exiting after a few sucessful operations

### ISSUE THREAD

**Issue by AlchemistTim** [noitcudni/bing-webmaster-tools-bulk-url-removal#2]
Great tool that I have used the tool successfully a few times. 

Today it has been failing after only a few operations.

I have included the developer's console logs for your inspection. I am also including the CSV file I am running for the removals.

[search.google.com-1672424851628.log](https://github.com/noitcudni/bing-webmaster-tools-bulk-url-removal/files/10325892/search.google.com-1672424851628.log)
[Removals_12_30_22.csv](https://github.com/noitcudni/bing-webmaster-tools-bulk-url-removal/files/10325894/Removals_12_30_22.csv)

**Comment by noitcudni** [comment]
My memory is a bit fuzzy. I think one of the options on bings removal tool
was straight up broken on bing’s side when I looked a couple months ago. I
will take a look again later tonight.

**Comment by AlchemistTim** [comment]
Thank you. It worked great the first couple of times. Hopefully the console dump will help or perhaps I've done something different and broken it.

No hurry. Probably won't get back to it until tuesday.

**Comment by AlchemistTim** [comment]
I just realized I posted this in the wrong area. I'm using the Google URL remover. If it matters, I'm reposting the issue in the google tool area.

Sorry.. Newbie here...

**Comment by noitcudni** [comment]
Can you try temporarily disabling all the other extensions and give it
another go?
