### ISSUE TITLE
Upload CSV Button Not Responding

### ISSUE THREAD

**Issue by ryan-umktg** [noitcudni/bing-webmaster-tools-bulk-url-removal#3]
I have used your Google tool for years without issue. When I try to use the Bing version, the 'Submit CSV file' button does not respond to clicks. I can't find any popups or anything that is being blocked. Can you help me?
https://capture.dropbox.com/BFWEJNlrlNZgkxEX

**Comment by abhranil26** [comment]
https://dc.services.visualstudio.com/v2/track

is being called which gives a HTTP 439 error

**Comment by noitcudni** [comment]
> https://dc.services.visualstudio.com/v2/track
> 
> is being called which gives a HTTP 439 error

@abhranil26 is it not working for you as well? Also, that has nothing to do with the CSV button issue. Please open another issue.

**Comment by noitcudni** [comment]
> I have used your Google tool for years without issue. When I try to use the Bing version, the 'Submit CSV file' button does not respond to clicks. I can't find any popups or anything that is being blocked. Can you help me? https://capture.dropbox.com/BFWEJNlrlNZgkxEX

Can you try disabling other extensions and give it another try?

**Comment by abhranil26** [comment]
@noitcudni  yeah even for me the upload csv thing is not working

**Comment by noitcudni** [comment]
> @noitcudni yeah even for me the upload csv thing is not working

Can you try disabling all other extensions and give it a try. I'll try to reproduce the issue on my end

**Comment by noitcudni** [comment]
Also, try refreshing the https://www.bing.com/webmasters/searchconfig/blockurl page

**Comment by abhranil26** [comment]
I disabled every extension and also refreshed that page multiple times, didn't work.

**Comment by abhranil26** [comment]
Also for loading unpacked extension i had to remove the line   "default_locale": "en", otherwise kept getting this error - Default locale was specified, but _locales subtree is missing.
Could not load manifest.

**Comment by noitcudni** [comment]
Oh, you didn't get the one from Chrome webstore? I haven't been updating the one on github.

**Comment by ryan-umktg** [comment]
I tried installing in a Chrome browser with no other plugins, on a machine where this plugin was never previously installed. Still not clickable. I don't see any error events in the Console or Network tab (besides bing's own error mentioned before).

**Comment by noitcudni** [comment]
Did you get it from Google’s web store?

**Comment by ryan-umktg** [comment]
Yes, I used the link in your earlier reply. Is that correct?

**Comment by noitcudni** [comment]
Just wanted to double check which link? [This one](https://chrome.google.com/webstore/detail/bing-webmaster-tools-bulk/knhcaipgfilkpgkejhmjbgklpalkaahi)?

**Comment by noitcudni** [comment]
Can you try refreshing the page? And see if that works? 

You can ping me directly at lihster.developer@gmail.com.

**Comment by noitcudni** [comment]
@ryan-umktg I just recently updated the extension. The problem should be fixed. Can you give it a try?

**Comment by ryan-umktg** [comment]
@noitcudni Yes, the new version fixed it. I had to wait a little bit for it to open the first time, but after that it works as expected. Thank you!

**Comment by noitcudni** [comment]
Thanks for confirming.
